<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <!-- Fiksuota 3.3.1 — suderinta su kolega; 3.4.0 jau reikalauja .NET 10 -->
    <PackageReference Include="SteamKit2" Version="3.3.1" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>
</Project>
