# Cloudflare Pages Configuration
name = "armamods-leaderboard"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-24"

# KV Namespace for mods, servers and history
[[kv_namespaces]]
binding = "TRENDING_KV"
id = "a8f21c595e39452e95e7e41e3d812013"

[vars]
ENVIRONMENT = "production"
WEBHOOK_SECRET = "REPLACE_WITH_SECRET"
# WORKER_URL is no longer needed as we use internal Functions
